package com.qvd.smartswitch.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qvd.smartswitch.model.DeviceLogVo;
import com.qvd.smartswitch.model.DeviceNickNameVo;
import com.qvd.smartswitch.model.DeviceTimgTimeVo;

import com.qvd.smartswitch.dao.DeviceLogVoDao;
import com.qvd.smartswitch.dao.DeviceNickNameVoDao;
import com.qvd.smartswitch.dao.DeviceTimgTimeVoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceLogVoDaoConfig;
    private final DaoConfig deviceNickNameVoDaoConfig;
    private final DaoConfig deviceTimgTimeVoDaoConfig;

    private final DeviceLogVoDao deviceLogVoDao;
    private final DeviceNickNameVoDao deviceNickNameVoDao;
    private final DeviceTimgTimeVoDao deviceTimgTimeVoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceLogVoDaoConfig = daoConfigMap.get(DeviceLogVoDao.class).clone();
        deviceLogVoDaoConfig.initIdentityScope(type);

        deviceNickNameVoDaoConfig = daoConfigMap.get(DeviceNickNameVoDao.class).clone();
        deviceNickNameVoDaoConfig.initIdentityScope(type);

        deviceTimgTimeVoDaoConfig = daoConfigMap.get(DeviceTimgTimeVoDao.class).clone();
        deviceTimgTimeVoDaoConfig.initIdentityScope(type);

        deviceLogVoDao = new DeviceLogVoDao(deviceLogVoDaoConfig, this);
        deviceNickNameVoDao = new DeviceNickNameVoDao(deviceNickNameVoDaoConfig, this);
        deviceTimgTimeVoDao = new DeviceTimgTimeVoDao(deviceTimgTimeVoDaoConfig, this);

        registerDao(DeviceLogVo.class, deviceLogVoDao);
        registerDao(DeviceNickNameVo.class, deviceNickNameVoDao);
        registerDao(DeviceTimgTimeVo.class, deviceTimgTimeVoDao);
    }
    
    public void clear() {
        deviceLogVoDaoConfig.clearIdentityScope();
        deviceNickNameVoDaoConfig.clearIdentityScope();
        deviceTimgTimeVoDaoConfig.clearIdentityScope();
    }

    public DeviceLogVoDao getDeviceLogVoDao() {
        return deviceLogVoDao;
    }

    public DeviceNickNameVoDao getDeviceNickNameVoDao() {
        return deviceNickNameVoDao;
    }

    public DeviceTimgTimeVoDao getDeviceTimgTimeVoDao() {
        return deviceTimgTimeVoDao;
    }

}
